### ISSUE TITLE
Is this ros driver suitable for ati-mini45 sensor?

### ISSUE THREAD

**Issue by ckyrepo** [KITrobotics/ati_force_torque#6]
Dear sir,  
I'm going to read the data from the ati-mini45 sensor using ROS, and i'm wondering if this package can be used in the situation?  Is there any tutorials that describing how to set up corresponding stuffs? I'm currently just connect the sensor through USB port with my laptop( running ubuntu16.04 with ros kinetic) . Thanks a lot.

**Comment by destogl** [comment]
This is exacly driver for that.
